schema_version = "1.0.0"

id = "pataz_anim_toolz"
version = "0.0.8"
name = "Pataz Anim Toolz"
tagline = "Animation tools"
maintainer = "Beorn Leonard"
type = "add-on"

website = "https://patazanimation.com/"

tags = ["Animation"]

blender_version_min = "4.2.0"
blender_version_max = "4.5.9"

license = ["SPDX:GPL-3.0-or-later"]
